Vagrant.configure("2") do |config|
    (1..3).each do |i|
        config.vm.define "master-#{i}" do |master|
            master.vm.box = "ubuntu/jammy64"
            master.vm.hostname = "master-#{i}"
            master.vm.network "public_network",
              ip: "192.168.0.21#{i}",
              bridge: "MediaTek Wi-Fi 6 MT7921 Wireless LAN Card"

            master.ssh.insert_key = false
            master.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
            master.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
            # master.vm.provision "shell", path: "common.sh"
            # master.vm.provision "shell", path: "master.sh"
            master.vm.provider "virtualbox" do |vb|
              vb.gui = false
              vb.cpus = 2
              vb.memory = 2048
            end
        end
    end

    (1..3).each do |i|
        config.vm.define "worker-#{i}" do |worker|
            worker.vm.box = "ubuntu/jammy64"
            worker.vm.hostname = "worker-#{i}"
            worker.vm.network "public_network",
              ip: "192.168.0.22#{i}",
              bridge: "MediaTek Wi-Fi 6 MT7921 Wireless LAN Card"

            worker.ssh.insert_key = false
            worker.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
            worker.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
            # worker.vm.provision "shell", path: "common.sh"
            # worker.vm.provision "shell", path: "worker.sh"

            worker.vm.provider "virtualbox" do |vb|
              vb.gui = false
              vb.cpus = 1
              vb.memory = 2048
            end
        end
    end
end
